fix: scales.html not loading in production
adobe/leonardo pull request #237
Opened 2024-03-19 11:44 UTC by karstens

## Description

## Motivation

## Screenshots

## To-do list

- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] This pull request is ready to merge.

2024-03-19 11:44 UTC, GarthDB commented
<!-- moon-run-report: unknown -->

## Run report for [ce4fef7e](https://github.com/adobe/leonardo/commit/ce4fef7ed62ec8164368174c14661aaceed8e1fb)
Total time: 18.8s | Comparison time: 17.4s | Estimated loss: 1.4s (7.6% slower)
|     | Action | Time | Status | Info |
| :-: | :----- | ---: | :----- | :--- |
| 🟩 | `SyncWorkspace` | 0ms | Passed |  |
| ⬛️ | `SetupNodeTool(~20.11)` | 1.1s | Skipped |  |
| 🟩 | `InstallNodeDeps(~20.11)` | 7.8s | Passed |  |
| 🟩 | `SyncNodeProject(contrast-colors)` | 0.1ms | Passed |  |
| 🟩 | `SyncNodeProject(ui)` | 0.3ms | Passed |  |
| 🟩 | `RunTask(ui:makeDistDir)` | 35ms | Passed |  |
| 🟩 | `RunTask(ui:copyCNAME)` | 20.5ms | Passed |  |
| 🟩 | `RunTask(ui:copyUIIcons)` | 59.6ms | Passed |  |
| 🟩 | `RunTask(ui:copyWorkflowIcons)` | 50.4ms | Passed |  |
| 🟩 | `RunTask(ui:buildSite)` | 9.9s | Passed |  |

<details><summary><strong>Touched files</strong></summary><div>

```
docs/ui/README.md
docs/ui/moon.yml
docs/ui/src/js/createHtmlElement.js
```

</div></details>

2024-03-19 12:11 UTC, karstens commented on docs/ui/src/js/createHtmlElement.js
> +  if (className) el.setAttribute('class', className);
See https://developer.mozilla.org/en-US/docs/Web/API/Element/className?retiredLocale=de#notes

2024-03-20 17:03 UTC, GarthDB requested changes
@karstens, Could you add a [Changeset](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md)?

2024-03-21 15:20 UTC, GarthDB approved these changes

2024-03-21 15:21 UTC, merged